Thresholding of isosurface without creating a new one
rcassani/brainstorm3 pull request #31
Opened 2024-08-09 18:11 UTC by chinmaychinara91

- [ ] remove the threshold isosurface slider feature from `Surface` tab
 - [ ] add a pop up UI or maybe a menu item to change isosurface mesh in the figure window itself
 - [x] remove deleting and regeneration of isosurface file rather just update the surface data in the already present file
 
 Other related issues:
 - [x] for SEEG implantation, prevent loading multiple instances of the same figure (isosurface+MRI Viewer)

2024-08-09 22:18 UTC, chinmaychinara91 commented
@rcassani I have added something like this (a menu pop up on right clicking on the 3D figure when isosurface is displayed):
![Screenshot 2024-08-09 151712](https://github.com/user-attachments/assets/161516b9-2367-4cb3-83a6-4d64b6881769)

It is ready for review. Might need some more code cleanup. But if you can test the basic functionalities and let me know I can go forward with cleaning up.

2024-08-12 22:42 UTC, chinmaychinara91 commented on toolbox/gui/figure_3d.m
> +        % jButtonSet = gui_component('button', [], '', 'Set', [], [], @(h,ev)tess_isosurface(CtFile, jSpinner.getValue()));
also removed the need to another button click

2024-08-21 20:11 UTC, rcassani commented
This crashes if there is already a `isoSurface` in the Subject's anatomy and CT segmentation is started from CT volume with right-click > CT segmentation > Generate threshold mesh from CT

@chinmaychinara91, @tmedani, Did you use the proposed changes to search for the ideal threshold value from a CT where the ideal threshold is not known?

I did, and I found quite cumbersome to search for the desired threshold value. While the changes in this PR remove the slider from the Surface, the proposed input in the context menu does not accept an arbitrary number just pre-defined +-50 steps with the up/down arrows; similar to the key shortcuts, but for some reason there the steps are +-100. 

Let's keep the slider in the Surface tab for now.
What do you think?

2024-08-21 21:11 UTC, chinmaychinara91 commented
> This crashes if there is already a `isoSurface` in the Subject's anatomy and CT segmentation is started from CT volume with right-click > CT segmentation > Generate threshold mesh from CT

Fixed. check [dc3ccce](https://github.com/rcassani/brainstorm3/pull/31/commits/dc3cccee3d22b302d1cea38046f183967bffee15)

> @chinmaychinara91, @tmedani, Did you use the proposed changes to search for the ideal threshold value from a CT where the ideal threshold is not known? I did, and I found quite cumbersome to search for the desired threshold value.

So from the feedback from Johnson on how the isoValue threshold is used when doing manual labelling is there is no one isoValue that we can say is the best. There could be some ideal cases but in reality the isovalue threshold might need adjustment while localizing every contact. He has been using 3D slicer to do the same thing and it does something similar but they have a slider feature for threshold and the mesh generation is faster/almost real time there probably because of C++.  Maybe we can adjust the increment numbers from 50/100 to something better.

> the proposed input in the context menu does not accept an arbitrary number just pre-defined +-50 steps with the up/down arrows; similar to the key shortcuts, but for some reason there the steps are +-100.

Yes this is not an editable text field rather it reads the current isoValue from the comment and updates it as the initial value. Discussed this with @tmedani,  the up down arrows in the context menu can then be used is for fine tuning by +-50. The shortcut keys (shift+up/down) is for a coarser tuning +-100. Just chose these values arbitrarily but we can come up with a better number. Do you think we should have it as an editable field so that people can enter values into it directly? 

> Let's keep the slider in the Surface tab for now.

I feel we should test and debug this approach and remove the slider option from Surface tab.

Let me know what you think.

2024-08-21 21:53 UTC, tmedani commented
Hey guys @chinmaychinara91 @rcassani 
Sorry for not being so active here!


From user perspective (and from what we have previously discussed), it is better to have this shortcut active.
(If its implementation is not hurting any other part of the code)

The CTs do not have fixed threshold, each electrode or even each contact may need a different threshold to be visible. Using the shift+up/down is faster for visual inspection and then contact editing,  also this is inline with what 3D slicer uses, 
and what some clinicians are expecting: just shortcuts and less-click and menus. 

As @chinmaychinara91 proposed, we can increase the steps [+/-100] and keep the menu for fine tuning if required. 

I will double check with Chinmay later today about the values.

2024-08-22 15:06 UTC, rcassani commented
@chinmaychinara91, @tmedani 
If you have tested and think that's a good usability, that's ok for me.
Then let me know when the code is read to be reviewed.

2024-08-23 23:19 UTC, chinmaychinara91 commented
@rcassani this is ready for review.

2024-09-06 15:14 UTC, rcassani requested changes
It works as it should. There is a bug with the wrong selection of CT file, this is one of the items reported in the PR (https://github.com/brainstorm-tools/brainstorm3/pull/732) and needs to be solved.

While the code does not delete and create a new isosurface file. If does rewrite the content at every change. Is there a value on doing this?

Personally, I found more useful the slider implementation, it allows to do big jumps in the threshold to do binary search of thresholds for identify contacts.

@chinmaychinara91, Did you take a look to the GUI of the "Edit MRI registration" as I asked you before doing these changes? 
https://neuroimage.usc.edu/brainstorm/Tutorials/Yokogawa#Refine_the_MRI_registration

We can do this kind of GUI, to provide tools  to manipulate the isosurface to locate electrodes, just to mention some:

* threshold slider
* presets to thresholds, so once user identifies them
* turn on/off the centroid option
* the get coordinates cross (since the iEEG can be open without 3D figures)
* and others

Also, all the manipulations would not need to save any change in disk, as the relevant information is the electrode positions, not the changes in the isosurface.

(Proof of concept)
![image](https://github.com/user-attachments/assets/b7c0c7e7-42e2-4674-9e43-b2e4260ad682)

@tmedani, any thoughts?

2024-09-06 15:14 UTC, rcassani commented on toolbox/gui/figure_3d.m
> +                    elseif ismember('shift', keyEvent.Modifier) && ~isempty(iIsoSurf)
Simplify to `elseif ismember('shift', keyEvent.Modifier)`, inside that condition, then check if there is CT isosurface, otherwise do nothing.
This leave the option of other shift actions in the future.

2024-09-06 15:14 UTC, rcassani commented on toolbox/gui/figure_3d.m
> +                    % Check if there is SEEG isosurface displayed on the figure
This will be check in the `shift` condtion.
See: comment for line 1081

2024-09-06 15:14 UTC, rcassani commented on toolbox/gui/figure_3d.m
> +    TessInfo = getappdata(hFig, 'Surface');
This will be check in the `shift` condtion.
See: comment for line 1081

2024-09-06 15:14 UTC, rcassani commented on toolbox/gui/figure_3d.m
> +                        CtFile = sSubject.Anatomy(iCt(1)).FileName;
This is a bug reported in the PR2

> Wrong CT volume can be selected thresholding CT with slider
This can happen if there are more than one CT in the Subject. For example is isosurface is create from popmenu on the 2nd CT (in the image below) using the arrows or the popmenu to change the threshold will do it for the 1st CT.

![image](https://github.com/user-attachments/assets/342df57a-5b39-4009-ab78-f3ef7e9e683b)

A better way to fix this would be to add the filename of the CT that gave origin to the isosurface in the isosurface structure. Maybe in the history

2024-09-06 15:14 UTC, rcassani commented on toolbox/gui/figure_3d.m
> +        CtFile = sSubject.Anatomy(iCt(1)).FileName;
Same potential problem on getting the wrong CT

2024-09-06 15:55 UTC, chinmaychinara91 commented
@rcassani thank you for the detailed feedback. I will discuss these with @tmedani and get back to you.

2024-09-11 22:19 UTC, chinmaychinara91 commented
> @chinmaychinara91, Did you take a look to the GUI of the "Edit MRI registration" as I asked you before doing these changes? https://neuroimage.usc.edu/brainstorm/Tutorials/Yokogawa#Refine_the_MRI_registration
> 
> We can do this kind of GUI, to provide tools to manipulate the isosurface to locate electrodes, just to mention some:
> 
> * threshold slider
> * presets to thresholds, so once user identifies them
> * turn on/off the centroid option
> * the get coordinates cross (since the iEEG can be open without 3D figures)
> * and others
> 
> Also, all the manipulations would not need to save any change in disk, as the relevant information is the electrode positions, not the changes in the isosurface.
> 
> (Proof of concept) ![image](https://private-user-images.githubusercontent.com/8238803/365214712-b7c0c7e7-42e2-4674-9e43-b2e4260ad682.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYwOTE4MDMsIm5iZiI6MTcyNjA5MTUwMywicGF0aCI6Ii84MjM4ODAzLzM2NTIxNDcxMi1iN2MwYzdlNy00MmUyLTQ2NzQtOWU0My1iMmU0MjYwYWQ2ODIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MTFUMjE1MTQzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTQ4MzU2OThmMTc5NGMyYjgzOTkzZjNjY2ZmOWQ2YmViNjViZGRkMGFjOTFiM2NlOTI3MjZlMjA2NWE1MmI0MCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.2LcXoD5rt-0VGC-4n71f6uGJw9xm6SDdMEqRDyLEXIM)

We agree with your proposal. Let me work on it. This sounds more user friendly.

2024-11-04 19:43 UTC, chinmaychinara91 commented
> https://neuroimage.usc.edu/brainstorm/Tutorials/Yokogawa#Refine_the_MRI_registration
> 
> We can do this kind of GUI, to provide tools to manipulate the isosurface to locate electrodes

closing this PR. Will start a separate PR based on the above recommendation

2024-11-04 19:43 UTC, closed without merging