Ftr restructure
rcassani/brainstorm3 pull request #5
Opened 2021-09-28 21:41 UTC by rcassani

2021-10-01 04:13 UTC, martcous requested changes
Nicely done, Ray, looks like reasonable changes to me. I have a few minor comments. I went through the whole code by I don't have time to fully test this right now. Let me know if you need my help with this.

2021-10-01 04:13 UTC, martcous commented on toolbox/db/db_add_condition.m
>      SubjectName = sSubject.Name;
Don't you need to specify Name as a column to fetch here? Otherwise it won't be defined.

2021-10-01 04:13 UTC, martcous commented on toolbox/db/db_get.m
> +                        tmp.UseDefaultChannel = sSubjects(i).UseDefaultChannel;
Duplicated line here.

2021-10-01 04:13 UTC, martcous commented on toolbox/db/db_set.m
> +    % [Sucess]               db_set('Subject', 'Delete', CondQuery)
Typo here: Sucess -> Success

2021-10-01 04:13 UTC, martcous commented on toolbox/db/db_set.m
> +            if ~exist('iSubject','var')
FYI, while this may be working fine, it's not really a good programming practice to check for existence of a variable. You never know if this is set in another part of this file or as a global variable. It's much safer to do:
```
if length(args) > 1
    iSubject = args{2};
else
    iSubject = [];
end

if isempty(iSubject)
    % ...
```

2021-10-01 04:13 UTC, martcous commented on toolbox/db/db_set.m
> +            if ~exist('iSubject','var')
Same comment as above.

2021-10-01 04:13 UTC, martcous commented on toolbox/db/db_set.m
> +                end
I think something's a bit off in the logic here. What if the condition is skipped? No error message? And resUpdate is undefined?

2021-10-01 04:13 UTC, martcous commented on toolbox/db/db_set.m
> +    case 'AnatomyFile'
All my comments of `db_set('Subject')` also apply here.

2021-10-01 04:13 UTC, martcous commented on toolbox/db/db_surface_default.m
> +lock_release([], LockId);
Might as well reuse `sqlConn` from above.

2021-10-01 04:13 UTC, martcous commented on toolbox/db/db_convert_anatomyfile.m
> +% Bidirectional conversion between Old and New structures
You'll want to add Brainstorm's copyright here. Great function BTW!

2021-10-01 04:13 UTC, martcous commented on toolbox/db/db_get.m
> +        end
I'm not sure this part making sure a protocol is loaded is relevant to be included in `db_get()`.

2021-10-02 15:39 UTC, rcassani commented on toolbox/db/db_set.m
> +            if ~exist('iSubject','var')
Thanks for advise!

2021-10-02 15:45 UTC, rcassani commented on toolbox/db/db_set.m
> +                end
An error is now prompted indicating that it's not possible to update due to incorrect Id

2021-10-02 15:49 UTC, rcassani commented on toolbox/db/db_surface_default.m
> +lock_release([], LockId);
Agree.
In similar way it would be worth it to add an optional sqlConn argument in lock_acquire()

2021-10-02 16:03 UTC, rcassani commented
Changes made in 6c2dea926df545febc45700960f7c1af0c4ea044.

2021-10-03 03:20 UTC, martcous approved these changes
Great work, Ray! Looks good!

2021-10-04 14:55 UTC, merged